apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: java-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: java-api
                  operator: In
                  values:
                  - java-api
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers: 
        - name: java-api
          image: gcr.io/PROJECTNAME/revolut:TRAVIS_COMMIT
          ports:
            - name: http
              containerPort: 4567
          volumeMounts:
          - name: api-disk
            mountPath: "/opt/"    
      volumes:
      - name: api-disk
        persistentVolumeClaim:
          claimName: api-disk
        
---
apiVersion: v1
kind: Service
metadata: 
  name: java-api
  labels: 
    name: java-api
spec:
  ports:
    - name: http
      port: 4567
      targetPort: 4567
  selector: 
    name: java-api
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-disk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
      